name: Build OpenWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev gawk git unzip file wget python3

    - name: Clone OpenWrt source
      run: git clone https://github.com/openwrt/openwrt.git

    - name: Prepare build config
      run: |
        cp .config openwrt/.config
        make -C openwrt defconfig

    - name: Build firmware
      run: make -C openwrt -j$(nproc)

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/**/
