name: Build OpenWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true 
        clean: false

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev gawk git unzip file wget python3 rsync

    - name: Clone OpenWrt source
      run: git clone https://github.com/openwrt/openwrt.git

    - name: Build and Configure OpenWrt
      run: |
        cd openwrt
        # 1. Copy the clean config file
        cp ../config_config .config

        # 2. Update and install feeds
        ./scripts/feeds update -a 
        ./scripts/feeds install -a
        
        # 3. Finalize configuration non-interactively to avoid failure
        yes "" | make oldconfig   
        
        # 4. Check and install all necessary prerequisites
        make prereq

        # 5. Start build process (Optimal speed)
        make -j$(nproc)

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        # Upload only the IPQ807x/SDXLEMUR target files
        path: openwrt/bin/targets/ipq807x/generic/
        
