name: Build OpenWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev gawk git unzip file wget python3

    - name: Clone OpenWrt source
      run: git clone https://github.com/openwrt/openwrt.git

    - name: Prepare build config
      working-directory: openwrt
      run: |
        cp ../.config .config
        make defconfig

    - name: Build firmware
      working-directory: openwrt
      run: make -j$(nproc)

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/
        path: openwrt/bin/targets/**/
