name: Build OpenWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev gawk git unzip file wget

    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        cp ../.config .config
        make defconfig
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/
