name: Build OpenWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        clean: false

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses5-dev gawk git unzip file wget python3 rsync

    - name: Clone OpenWrt source
      run: git clone https://github.com/openwrt/openwrt.git

    - name: Build and Configure OpenWrt
      run: |
        cp .config openwrt/.config
        make -C openwrt defconfig
        make -C openwrt scripts/feeds update -a
        make -C openwrt scripts/feeds install -a
        make -C openwrt -j$(nproc)

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/
        
